[package]
name = "hnefatafl-rs-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version ="4", features = ["derive"] }
hnefatafl = "0.0.1"
hnefatafl-copenhagen = "0.8"
hnefatafl-egui = { version = "0.1", git = "https://github.com/dcampbell24/hnefatafl-egui/" }
